title: Mustafa Ali # your name (or website title) here
logo: "/images/IMG_8649.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Field of expertises 
  <br>Studing a M.Sc in information technology<br>
  <a href=www.linkedin.com/in/mustafa-ali-8841ba19a/>View My LinkedIn Profile</a> 
  
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
theme: jekyll-theme-minimal
