title: Mustafa Ali # your name (or website title) here
logo: "/images/IMG_8649.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Field of expertises 
  <br>I am an engineer student at the royal institue of technology, studing a M.Sc in information technology<br>
  Hobbies 
  <br>My hobbies include programming, training and spending time with friends <br>
  <a href="www.linkedin.com/in/mustafa-ali-8841ba19a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
